# Generated by Django 5.0.6 on 2024-06-11 18:46

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_page_options_alter_page_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=django_quill.fields.QuillField(verbose_name='Contenido'),
        ),
    ]
